# Generated by Django 4.1.13 on 2024-07-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
