# Generated by Django 2.2.7 on 2024-05-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projeto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to='./static/img'),
        ),
    ]
