# Generated by Django 2.2.7 on 2024-05-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20240522_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
