# Generated by Django 2.2.7 on 2024-05-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20240528_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['titulo']},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['id']},
        ),
    ]
