# Generated by Django 2.2.7 on 2024-05-30 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20240529_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['-id']},
        ),
    ]
