# Generated by Django 5.0.6 on 2024-05-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20240530_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to='./'),
        ),
    ]
