# Generated by Django 5.0.6 on 2024-06-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_projeto_imagem_projeto_imagem_dropbox_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to='static/media'),
        ),
    ]
