# Generated by Django 5.0.6 on 2024-06-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_projeto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='imagem_dropbox_path',
        ),
    ]
