# Generated by Django 5.0.6 on 2024-06-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_remove_projeto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='url',
            new_name='imagem',
        ),
        migrations.AddField(
            model_name='projeto',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
